ci: debug publish maccatalyst
References #609

diff --git a/.github/workflows/publish-mac-catalyst-pkg.yml b/.github/workflows/publish-mac-catalyst-pkg.yml
--- a/.github/workflows/publish-mac-catalyst-pkg.yml
+++ b/.github/workflows/publish-mac-catalyst-pkg.yml
@@ -141,23 +141,12 @@ jobs:
           publish_path='${{ env.publish-path }}'
           extra_options='${{ matrix.publish.extra }}'
 
-          echo "[$publish_path]"
-
           mkdir -p "${publish_path}"
-          ls -alR "./.publish"
-
-          pwd
 
           options="--output=$publish_path --configuration=$configuration --framework=$framework --property:Version=\"$semantic_version\" --property:AssemblyVersion=\"$numeric_version\""
           echo "$options  $extra_options" | xargs dotnet publish $project 
 
-          pwd
-
-          ls -alR "./.publish"
-
           rm -rf "$publish_path/*.pdb"
-
-          ls -alR "./.publish"
 
       - name: Prepare Artifacts
         shell: bash
@@ -166,16 +155,16 @@ jobs:
           publish_path="${{ env.publish-path }}"
           tool='${{ matrix.artifact.tool }}'
 
-          echo "[$publish_path]"
+          echo "publish_path: [$publish_path]"
 
-          pwd
+          echo "pwd: $(pwd)"
 
           mkdir -p "${artifact_path}"
 
           ls -alR "./.publish"
 
           if [[ "$tool" == "cp" ]]; then
-            cp -r "${publish_path}/*" "$artifact_path" && echo "Copying of the artifact has been completed successfully." || echo "::warning::Failed to copy artifact"
+            cp -r ${publish_path}/* ${artifact_path}/ && echo "Copying of the artifact has been completed successfully." || echo "::warning::Failed to copy artifact"
           else
             echo "::warning::Unknown artifact tool: '$tool'"
           fi
