ci: fix yml

diff --git a/.github/workflows/xaml-style-check.yml b/.github/workflows/xaml-style-check.yml
--- a/.github/workflows/xaml-style-check.yml
+++ b/.github/workflows/xaml-style-check.yml
@@ -109,7 +109,7 @@ jobs:
               mapfile -t -d ';' lines < <(echo -n $diff_lines)
 
               for line in "${lines[@]}"; do
-                echo "::error file=$xaml,line=$line,title=Invalid xaml style::Error"
+                echo "::error file=$xaml,line=$line,title=Invalid xaml style::Error xaml style"
               done
 
               echo "::debug::run diff"
@@ -125,3 +125,10 @@ jobs:
 
             echo "::debug::next xaml"
           done
+
+          echo "::debug::if correct"
+
+          if [ "$correct" = false ]; then
+            echo "::debug::exit"
+            exit 1
+          fi
